DROP DATABASE IF EXISTS tsukasadb;
CREATE DATABASE tsukasadb;
USE tsukasadb;

CREATE TABLE user(uid INT PRIMARY KEY NOT NULL AUTO_INCREMENT, gid INT NOT NULL DEFAULT 1, uname VARCHAR(30) NOT NULL, password VARCHAR(50) NOT NULL, mail VARCHAR(100) NOT NULL, address VARCHAR(100) NOT NULL DEFAULT "@", delete_flag INT NOT NULL DEFAULT 0);
CREATE TABLE shouhin(sid INT PRIMARY KEY NOT NULL AUTO_INCREMENT, sname VARCHAR(30) NOT NULL, cid INT NOT NULL DEFAULT 1, kakaku INT NOT NULL, setsumei TEXT, delete_flag INT NOT NULL DEFAULT 0);
CREATE TABLE category(cid INT PRIMARY KEY NOT NULL AUTO_INCREMENT, cname VARCHAR(30) NOT NULL, delete_flag INT NOT NULL DEFAULT 0);
CREATE TABLE rireki(rid INT PRIMARY KEY NOT NULL AUTO_INCREMENT, uid INT NOT NULL, hizuke DATETIME NOT NULL, sid INT NOT NULL);
